const NEW_DATA_LOADED = 'NEW_DATA_LOADED';
const DRAWER_TOGGLED = 'DRAWER_TOGGLED';
const NAME_CHANGED = 'NAME_CHANGED';
const SURNAME_CHANGED = 'SURNAME_CHANGED';
const MAIL_CHANGED = 'MAIL_CHANGED';
const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export { NEW_DATA_LOADED, DRAWER_TOGGLED, NAME_CHANGED, SURNAME_CHANGED, MAIL_CHANGED, PASSWORD_CHANGED };